name: Auto-Assign Picks Scheduler

# Este workflow se ejecuta cada 30 minutos durante días de partido (Jueves a Lunes)
# Verifica si es momento de ejecutar auto-assign-last-game-picks
on:
  schedule:
    # Ejecutar cada 30 minutos durante días de partido NFL
    # Jueves a Lunes: 10:00 AM - 2:00 AM (hora del servidor UTC)
    - cron: '*/30 16-23,0-8 * * 4,5,6,0,1'  # Jueves-Lunes, cada 30 min
  
  # Permitir ejecución manual
  workflow_dispatch:

jobs:
  check-and-execute:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verificar tiempo de ejecución
        id: check_schedule
        run: |
          echo "🕐 Consultando schedule desde API..."
          
          RESPONSE=$(curl -s -X GET "https://${{ secrets.VERCEL_DOMAIN }}/api/get-auto-assign-schedule")
          echo "Response: $RESPONSE"
          
          # Extraer should_execute_now
          SHOULD_EXECUTE=$(echo $RESPONSE | jq -r '.should_execute_now // false')
          MINUTES_UNTIL=$(echo $RESPONSE | jq -r '.minutes_until_execution // 999')
          EXECUTION_TIME=$(echo $RESPONSE | jq -r '.execution_time // "unknown"')
          CURRENT_WEEK=$(echo $RESPONSE | jq -r '.current_week // 0')
          
          echo "should_execute=$SHOULD_EXECUTE" >> $GITHUB_OUTPUT
          echo "minutes_until=$MINUTES_UNTIL" >> $GITHUB_OUTPUT
          echo "execution_time=$EXECUTION_TIME" >> $GITHUB_OUTPUT
          echo "current_week=$CURRENT_WEEK" >> $GITHUB_OUTPUT
          
          echo "📊 Semana actual: $CURRENT_WEEK"
          echo "⏰ Tiempo de ejecución: $EXECUTION_TIME"
          echo "⏳ Minutos restantes: $MINUTES_UNTIL"
          echo "✅ ¿Ejecutar ahora?: $SHOULD_EXECUTE"

      - name: Ejecutar auto-assign si es tiempo
        if: steps.check_schedule.outputs.should_execute == 'true'
        run: |
          echo "🚀 EJECUTANDO AUTO-ASSIGN para semana ${{ steps.check_schedule.outputs.current_week }}"
          
          RESPONSE=$(curl -s -X POST "https://${{ secrets.VERCEL_DOMAIN }}/api/auto-assign-last-game-picks")
          echo "Response: $RESPONSE"
          
          # Verificar si fue exitoso
          STATUS=$(echo $RESPONSE | jq -r '.status // "error"')
          PICKS_ASSIGNED=$(echo $RESPONSE | jq -r '.picks_assigned // 0')
          
          if [ "$STATUS" = "completed" ]; then
            echo "✅ Auto-assign completado exitosamente"
            echo "📊 Picks asignados: $PICKS_ASSIGNED"
          else
            echo "⚠️ Auto-assign retornó status: $STATUS"
            echo "📊 Picks asignados: $PICKS_ASSIGNED"
          fi

      - name: Esperar siguiente verificación
        if: steps.check_schedule.outputs.should_execute == 'false'
        run: |
          echo "⏸️ Aún no es tiempo de ejecutar"
          echo "⏳ Faltan ${{ steps.check_schedule.outputs.minutes_until }} minutos"
          echo "⏰ Ejecución programada para: ${{ steps.check_schedule.outputs.execution_time }}"
          echo "🔄 Próxima verificación en 30 minutos"

  notify-on-failure:
    needs: [check-and-execute]
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Notificar fallo
        run: |
          echo "❌ ERROR en auto-assign-scheduler"
          echo "⚠️ Revisar logs del workflow"
          # Aquí puedes agregar notificaciones por email, Slack, etc.
